### ISSUE TITLE
No skin visible

### ISSUE THREAD

**Issue by DevDokus** [DokusCore/DokusCore--SkinCreator#3]
When users do not select a skin in the skin creator, no skin can be loaded in the game. We need to make sure that either the user is unable to proceed is the 4 critical values are not selected, or that a default skin is inserted when nothing is selected

**Comment by kalekaneki** [comment]
Can we do this through setting a default value in the sql db?

**Comment by DevDokus** [comment]
Checks have been set in place to prevent loading in without the correct skin settings set.
